using System;
using NssIT.Kiosk.AppDecorator.Common.AppService.Network;

namespace NssIT.Kiosk.AppDecorator.Common.AppService
{
	public interface INetCommandDirective
	{
		/// <summary>
		/// New Net Process Id. Should be auto generated by the class which is implementing this property.
		/// </summary>
		Guid BaseNetProcessId { get; }
		CommunicationDirection CommuCommandDirection { get; }
	}
}